POST http://localhost:8080/admin/staff
Content-Type: application/json
Authorization: Basic admin 123456

{
  "fullName": "Nguyen Van D",
  "phone": "0901234561",
  "email": "employee4@gmail.com",
  "password": "123456"
}

###

GET http://localhost:8080/admin/staff
Authorization: Basic admin 123456

###
PUT http://localhost:8080/admin/staff/1
Authorization: Basic admin 123456
Content-Type: application/json

{
  "fullName": "Nguyen Van B",
  "phone": "0912345678",
  "email": "employee2@gmail.com",
  "password": "123456"
}

###
DELETE http://localhost:8080/admin/staff/1
Authorization: Basic admin 123456

###
PATCH http://localhost:8080/admin/staff/2/status?status=ACTIVE
Authorization: Basic admin 123456

###
PUT http://localhost:8080/admin/staff/1
Content-Type: application/json
Authorization: Basic admin 123456

{
  "fullName": "Nguyen Van A Updated",
  "phone": "0909999999",
  "email": "employee.updated@gmail.com"
}